name: Daily Staffing Data Sync

on:
  push:
    branches:
      - main  # Triggers the workflow every time you push code to main
  schedule:
    # Daily run at 09:00 AM Ottawa (13:00 UTC)
    - cron: '0 13 * * *'
  workflow_dispatch: # Keep this so you can still run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas requests plotly

      - name: Run python.py
        run: python python.py

      - name: Upload Results and Map
        uses: actions/upload-artifact@v4
        with:
          name: staffing-output-files
          path: |
            final_staffing_report.csv
            staffing_map.html
