name: Daily Staffing Data Sync

on:
  schedule:
    # This runs at 00:00 UTC every day (7:00 PM or 8:00 PM EST)
    - cron: '10 13 * * *'
  workflow_dispatch: # Allows you to run it manually from GitHub for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas requests plotly

      - name: Run python.py
        run: python python.py

      - name: Upload Results and Map
        uses: actions/upload-artifact@v4
        with:
          name: staffing-output-files
          path: |
            final_staffing_report.csv
            staffing_map.html
